# ==================================
# 1. 设置环境变量
# ==================================
export MS_PYNATIVE_GE=1

START_DEVICE_ID=0  # 指定使用的NPU集群起始编号
END_DEVICE_ID=8  # 指定使用的NPU集群终止编号
export DEVICE_ID=$START_DEVICE_ID


# ==================================
# 2. 推理参数设置
# ==================================
SAMPLING_TASK_NAME="Sampling task name"
BASE_CKPT="vallina sdxl weights"
LORA_CKPT_FILE=(
    lora_weight0.ckpt
    lora_weight1.ckpt
    ...
)
CONFIG_FILE=(
    cfg0.yaml
    cfg1.yaml
    ...
)
PROMPTS="Prompts lists text file, one row = one prompt"
SAMPLER="EulerAncestralSampler"
DISCRETIZATION="LegacyDDPMDiscretization"  # EDMDiscretization
TASK_TYPE="txt2img"
RATIO="1.0"
SAMPLE_STEP=20
SEED=0
NUM_ROWS=1  # rows of concated images generated by one prompt
NUM_COLS=1  # cols of concated images generated by one prompt



# ==================================
# 3. 推理
# ==================================
for ckpt in ${LORA_CKPT_FILE[@]}; do
    for cfg in ${CONFIG_FILE[@]}; do


        # ==================================
        # (1) 推理准备
        # ==================================
        sdxl_dir="$(dirname "$(dirname "$(readlink -f "$0")")")"
        ckpt_filename=$(echo "${ckpt}" | awk -F'/' '{print $NF}')
        cfg_filename=$(echo "${cfg}" | awk -F'/' '{print $NF}')
        demo_save_path=$sdxl_dir/demo/$SAMPLING_TASK_NAME/${ckpt_filename}@${cfg_filename}@${SAMPLER}@${SAMPLE_STEP}steps
        tmp_dir=$sdxl_dir/tmp/$SAMPLING_TASK_NAME/${ckpt_filename}@${SAMPLER}@${SAMPLE_STEP}steps
        test -d $demo_save_path && demo_save_path=${demo_save_path}@$(date +'%Y-%m-%d-%H:%M:%S')
        test -d $tmp_dir || mkdir -p $tmp_dir
        mkdir -p $demo_save_path
        cd $tmp_dir
        export PYTHONPATH=$sdxl_dir:$PYTHONPATH


        # ==================================
        # (2) 推理
        # ==================================
        python $sdxl_dir/demo/sampling_without_streamlit.py \
        --task $TASK_TYPE \
        --config $cfg \
        --weight ${BASE_CKPT},${ckpt} \
        --sampler $SAMPLER \
        --sample_step $SAMPLE_STEP \
        --discretization $DISCRETIZATION \
        --seed $SEED \
        --prompt "$PROMPTS" \
        --device_target Ascend \
        --save_path $demo_save_path \
        --num_rows $NUM_ROWS \
        --num_cols $NUM_COLS \
        --sd_xl_base_ratios $RATIO \
        > $demo_save_path/log.txt 2>&1 &


        # ==================================
        # (3) 更新DEVICE_ID
        # ==================================
        NEW_DEVICE_ID=$(($DEVICE_ID + 1))
        if [ "$NEW_DEVICE_ID" == "$END_DEVICE_ID" ]; then
            NEW_DEVICE_ID=$START_DEVICE_ID
            wait
        fi
        export DEVICE_ID=$NEW_DEVICE_ID


    done
done
