# ==================================
# 1. 设置环境变量 [只需关注 DEVICE_ID]
# ==================================
export MS_PYNATIVE_GE=1
export DEVICE_ID=0  # 指定使用的NPU


# ==================================
# 2. 推理参数设置
# ==================================
SAMPLING_TASK_NAME="Sampling task name"
CKPT_FILE="CKPT file to load, use comma(,) to separate multiple .ckpt files"
CONFIG_FILE="path/to/sdxl/configs/inference/sd_xl_base.yaml"
PROMPTS="Prompts lists text file, one row = one prompt"
SAMPLER="EulerAncestralSampler"
TASK_TYPE="txt2img"
RATIO="1.0"
SAMPLE_STEP=20
SEED=0
NUM_ROWS=1  # rows of concated images generated by one prompt
NUM_COLS=1  # cols of concated images generated by one prompt


# ==================================
# 3. 推理准备
# ==================================
sdxl_dir="$(dirname "$(dirname "$(readlink -f "$0")")")"
ckpt_filename=$(echo "${CKPT_FILE}" | awk -F'/' '{print $NF}')
tmp_dir=$sdxl_dir/tmp/$SAMPLING_TASK_NAME/${ckpt_filename}@${SAMPLER}@${SAMPLE_STEP}steps
demo_save_path=$sdxl_dir/demo/$SAMPLING_TASK_NAME/${ckpt_filename}@${SAMPLER}@${SAMPLE_STEP}steps
test -d $demo_save_path && demo_save_path=${demo_save_path}@$(date +'%Y-%m-%d-%H:%M:%S')
test -d $tmp_dir || mkdir -p $tmp_dir
mkdir -p $demo_save_path
cd $tmp_dir
export PYTHONPATH=$sdxl_dir:$PYTHONPATH


# ==================================
# 4. 推理
# ==================================
python $sdxl_dir/demo/sampling_without_streamlit.py \
--task $TASK_TYPE \
--config $CONFIG_FILE \
--weight $CKPT_FILE \
--sampler $SAMPLER \
--sample_step $SAMPLE_STEP \
--seed $SEED \
--prompt "$PROMPTS" \
--device_target Ascend \
--save_path $demo_save_path \
--num_rows $NUM_ROWS \
--num_cols $NUM_COLS \
> $demo_save_path/log.txt 2>&1
